name: Scrape websites

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '0 0 * * 5'
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting env
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: 
          npm i
          node src/index.js